/* Copyright (C) 2013 Calvin Beck

  Permission is hereby granted, free of charge, to any person
  obtaining a copy of this software and associated documentation files
  (the "Software"), to deal in the Software without restriction,
  including without limitation the rights to use, copy, modify, merge,
  publish, distribute, sublicense, and/or sell copies of the Software,
  and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.

*/

#include "codegen.h"

#include <stdio.h>
#include <stdlib.h>
#include <mux_pipe.h>


/* Function to write the header and includes to the file */
static void write_header(FILE *output_file)
{
    char *comment = "/* File generated by the HubGen program by Calvin Beck */";

    char *include_arduino = "#include <Arduino.h>";
    char *include_pipes = "#include <mux_pipe.h>";
    char *include_muxduino = "#include <muxduino.h>";

    fprintf(output_file, "%s\n\n", comment);
    fprintf(output_file, "%s\n", include_arduino);
    fprintf(output_file, "%s\n", include_pipes);
    fprintf(output_file, "%s\n\n\n", include_muxduino);
}


/* Function to write a setup function to the output file */
static void write_setup(FILE *output_file, MuxPipe *pipes, size_t total_pipes)
{
    char *indent = "    ";  /* This is a bit silly... */

    fprintf(output_file, "void setup()\n{\n    MuxPipe pipe;\n");

    for (int index = 0; index < total_pipes; ++index) {
	/* Make all of the pipe registrations we need! */
	MuxPipe current = pipes[index];

	fprintf(output_file, "\n%spipe.in_pin = %d;\n", indent, current.in_pin);
	fprintf(output_file, "%spipe.out_pin = %d;\n", indent, current.out_pin);
	fprintf(output_file, "%spipe.channel = %d;\n", indent, current.channel);
	fprintf(output_file, "%sregister_pipe(pipe);\n", indent);
    }

    fprintf(output_file, "}\n\n");
}


/* Function to write a loop function to the output file */
static void write_loop(FILE *output_file)
{
    fprintf(output_file, "void loop()\n{\n    mux_update();\n}\n");
}


void write_arduino_code(FILE *output_file, MuxPipe *pipes, size_t total_pipes)
{
    write_header(output_file);
    write_setup(output_file, pipes, total_pipes);
    write_loop(output_file);
}
